# Welcome to Jekyll!

# Website settings
title: "yviedev"
description: "yviedev's blog."
keywords: "yviedev,blog,Jekyll,github,gh-pages"
baseurl: "/"
url: "http://yviedev.github.io"
# url: "http://127.0.0.1:4000"

# author
author:
  name: 'yvonne'
  first_name: 'yvonne'
  last_name: 'ike'
  email: 'yviedev@gmail.com'
  facebook_username: 'yvonneike'
  github_username: 'yviedev'
  head_img: 'static/img/landing/yvonne.jpg'
  desc: 'I am a Full-Stack engineer in training, speficially in website development with Ruby on Rails.'

# sections
sections:
  - id: 'about-me'
    i18n: 'nav.about_me'
    name: 'About'
    tpl: 'about.html'
    css: ''

  - id: 'projects'
    i18n: 'nav.projects'
    name: 'Projects'
    tpl: 'projects.html'
    css: 'project'
    
  - id: 'blog'
    i18n: 'nav.blog'
    name: 'Blog'
    tpl: 'blog.html'
    css: 'testimonials navy-section'
    
  - id: 'career'
    i18n: 'nav.career'
    name: 'Career'
    tpl: 'career.html'
    css: 'timeline'

  - id: 'skills'
    i18n: 'nav.skills'
    name: 'Skills'
    tpl: 'skills.html'
    css: 'team'

  # - id: 'links'
  #   i18n: 'nav.link'
  #   name: 'Links'
  #   tpl: 'links.html'
  #   css: 'contact'

# localization
languages:
  - locale: 'en'
    flag: 'static/img/flags/United-States.png'

# blog img path
# img_path: 'http://www.yviedev.github.io/static/img/blog'

# donate
# donate:
#   wechat: 'static/img/pay/wechat.png'
#   alipay: 'static/img/pay/alipay.png'

# comment
# changyan:
  # appid: cysfY7ULn
  # conf: prod_861928934cecb7a18e15bedaed9dae29
  
disqus:
  name: 'https-yviedev-github-io'
  # public_key: tj2MPaNlHMONwTH5bGDNSXyaBpW7q282MeUzh5CwcjJerNhK8Kxk3aWo7IckzTX7

# share
# bshare:
#   uuid: 513f778e-a8f7-4c20-9ec2-d29cc2328d75

# baidu analytics
# ba:
  # uuid: 317acca9ef9255b934e46371e471431d

# google analytics
# ga:
#   id: UA-73784599-1

# growingIO
# gio:
#   id: a49d4901c7853da9

# Build settings
encoding: "utf-8"

# other settings
highlighter: rouge
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
